
/* -------------------------------------------------------------------------
 * !!! AUTOMATICALLY GENERATED CODE !!!
 * -------------------------------------------------------------------------
 * This file was automatically generated by the OrangeBits compiler.  
 * Compiled on:  13/01/2013 02:07:43
 * Compiled by: ALEX-PC\Alex
 * Source: E:\Project\GitHub\SpaceTrekkers\client-src\js\nls\root\general.coffee      
 * -------------------------------------------------------------------------*/



define({
  app_title: "Space Trekkers",
  desktop: "Desktop",
  logout: "Logout",
  tree: "Tree",
  username_label: "Username",
  password_label: "Password",
  login_label: "Login",
  failed_login: "Failed login",
  attempting_login: "Logging in...",
  sign_up: "Sign Up",
  welcome_dialog_title: "Space Trekkers",
  welcome_dialog_text: "Welcome",
  logged_in_as: "Logged in as",
  loading: "Loading...",
  firstname_label: "First name",
  surname_label: "Surname",
  email_label: "Email"
});
