
/* -------------------------------------------------------------------------
 * !!! AUTOMATICALLY GENERATED CODE !!!
 * -------------------------------------------------------------------------
 * This file was automatically generated by the OrangeBits compiler.  
 * Compiled on:  12/01/2013 21:22:29
 * Compiled by: ALEX-PC\Alex
 * Source: E:\Project\MarionetteBase-Coffeescript\client-src\js\nls\root\general.coffee      
 * -------------------------------------------------------------------------*/



define({
  app_title: "Marionette+Bootstrap Base",
  desktop: "Desktop",
  logout: "Logout",
  tree: "Tree",
  username_label: "Username",
  password_label: "Password",
  login_label: "Login",
  failed_login: "Failed login",
  attempting_login: "Logging in...",
  welcome_dialog_title: "Welcome",
  welcome_dialog_text: "This is a working base containing the following :- RequireJS, Backbone, Marionette, Handlebars, Jasmine, jQuery, underscore  and Bootstrap",
  logged_in_as: "Logged in as",
  loading: "Loading..."
});
