
/* -------------------------------------------------------------------------
 * !!! AUTOMATICALLY GENERATED CODE !!!
 * -------------------------------------------------------------------------
 * This file was automatically generated by the OrangeBits compiler.  
 * Compiled on:  12/01/2013 21:22:29
 * Compiled by: ALEX-PC\Alex
 * Source: E:\Project\MarionetteBase-Coffeescript\client-src\js\nls\general.coffee      
 * -------------------------------------------------------------------------*/



define({
  root: true,
  "fr-fr": true
});
