
/* -------------------------------------------------------------------------
 * !!! AUTOMATICALLY GENERATED CODE !!!
 * -------------------------------------------------------------------------
 * This file was automatically generated by the OrangeBits compiler.  
 * Compiled on:  13/01/2013 01:39:03
 * Compiled by: ALEX-PC\Alex
 * Source: E:\Project\GitHub\SpaceTrekkers\client-src\js\nls\general.coffee      
 * -------------------------------------------------------------------------*/



define({
  root: true
});
