
/* -------------------------------------------------------------------------
 * !!! AUTOMATICALLY GENERATED CODE !!!
 * -------------------------------------------------------------------------
 * This file was automatically generated by the OrangeBits compiler.  
 * Compiled on:  12/01/2013 19:17:46
 * Compiled by: ALEX-PC\Alex
 * Source: E:\Project\MarionetteBase-Coffeescript\client-src\js\models\user\UserModel.coffee      
 * -------------------------------------------------------------------------*/



define(["backbone"], function(Backbone) {
  var userModel;
  userModel = Backbone.Model.extend({
    defaults: {
      username: "unknown",
      password: "unknown"
    },
    initialize: function(options) {
      this.username = options.username;
      this.password = options.password;
      return this;
    },
    url: function() {
      return "user?username=" + this.username + "&password=" + this.password;
    },
    attemptLogin: function() {
      return this.fetch({
        error: function(userModel, jqXHR, options) {
          return Backbone.Events.trigger("userModel:loginfailure", userModel);
        },
        success: function(userModel, response, options) {
          if (response.validLogin) {
            Backbone.Events.trigger("userModel:loginsuccess", userModel);
          }
          if (!response.validLogin) {
            return Backbone.Events.trigger("userModel:loginfailure", userModel);
          }
        }
      });
    }
  });
  return userModel;
});
