
/* -------------------------------------------------------------------------
 * !!! AUTOMATICALLY GENERATED CODE !!!
 * -------------------------------------------------------------------------
 * This file was automatically generated by the OrangeBits compiler.  
 * Compiled on:  12/01/2013 21:22:29
 * Compiled by: ALEX-PC\Alex
 * Source: E:\Project\MarionetteBase-Coffeescript\client-src\js\views\plainOldTemplate\PlainOldTemplate.coffee      
 * -------------------------------------------------------------------------*/



define(["jquery", "underscore", "backbone.marionette", "translationUtil"], function($, _, Marionette, TranslationUtil) {
  var plainOldTemplateView;
  plainOldTemplateView = Marionette.ItemView.extend({
    template: "<div>" + TranslationUtil.geti18nString('loading' + "</div>"),
    initialize: function(templateFileName) {
      var _template;
      _template = $.ajax({
        url: templateFileName,
        async: false
      });
      this.template = TranslationUtil.geti18nTemplate(_template.responseText);
      return this;
    }
  });
  return plainOldTemplateView;
});
