
/* -------------------------------------------------------------------------
 * !!! AUTOMATICALLY GENERATED CODE !!!
 * -------------------------------------------------------------------------
 * This file was automatically generated by the OrangeBits compiler.  
 * Compiled on:  12/01/2013 21:22:30
 * Compiled by: ALEX-PC\Alex
 * Source: E:\Project\MarionetteBase-Coffeescript\client-src\test\views\login\UserModel-Mock.coffee      
 * -------------------------------------------------------------------------*/



define(["backbone"], function(Backbone) {
  var userModelMock;
  userModelMock = Backbone.Model.extend({
    attemptLogin: function() {
      return Backbone.Events.trigger("userModel:attemptLogin", this);
    }
  });
  return userModelMock;
});
