
/* -------------------------------------------------------------------------
 * !!! AUTOMATICALLY GENERATED CODE !!!
 * -------------------------------------------------------------------------
 * This file was automatically generated by the OrangeBits compiler.  
 * Compiled on:  12/01/2013 21:22:30
 * Compiled by: ALEX-PC\Alex
 * Source: E:\Project\MarionetteBase-Coffeescript\client-src\test\utils\translationUtil-Mock.coffee      
 * -------------------------------------------------------------------------*/



define(["backbone"], function(Backbone) {
  var TranslationUtil;
  TranslationUtil = Backbone.Model.extend({
    geti18nString: function(value) {
      return value;
    },
    geti18nTemplate: function(template, options) {
      return template;
    }
  });
  return new TranslationUtil();
});
