
/* -------------------------------------------------------------------------
 * !!! AUTOMATICALLY GENERATED CODE !!!
 * -------------------------------------------------------------------------
 * This file was automatically generated by the OrangeBits compiler.  
 * Compiled on:  13/01/2013 02:01:21
 * Compiled by: ALEX-PC\Alex
 * Source: E:\Project\GitHub\SpaceTrekkers\client-src\js\views\login\LoginView.coffee      
 * -------------------------------------------------------------------------*/



define(["jquery", "underscore", "backbone.marionette", "text!templates/login/loginTemplate.html", "translationUtil", "bootstrap"], function($, _, Marionette, LoginTemplate, TranslationUtil) {
  var LoginView;
  LoginView = Marionette.ItemView.extend({
    template: TranslationUtil.geti18nTemplate(LoginTemplate),
    showFailedLoginMessage: function() {
      return $('#loginMessage').html(TranslationUtil.geti18nString("failed_login"));
    },
    hide: function() {
      return $("#mainLoginDiv").modal("hide");
    },
    onShow: function() {
      $("#mainLoginDiv").modal({
        keyboard: false,
        backdrop: 'static'
      });
      $("#loginButton").unbind('click').click(function(e) {
        e.preventDefault();
        return Backbone.Events.trigger("loginView:login");
      });
      $("#signupButton").unbind('click').click(function(e) {
        e.preventDefault();
        return Backbone.Events.trigger("loginView:signup");
      });
      $('#username').focus();
      $('#password').keypress(function(e) {
        if (e.which === 13) return $("#loginButton").click();
      });
      return this;
    }
  });
  return LoginView;
});
