
/* -------------------------------------------------------------------------
 * !!! AUTOMATICALLY GENERATED CODE !!!
 * -------------------------------------------------------------------------
 * This file was automatically generated by the OrangeBits compiler.  
 * Compiled on:  12/01/2013 21:22:29
 * Compiled by: ALEX-PC\Alex
 * Source: E:\Project\MarionetteBase-Coffeescript\client-src\js\nls\fr-fr\general.coffee      
 * -------------------------------------------------------------------------*/



define({
  app_title: "Marionette Base",
  desktop: "Le Desktop",
  logout: "Le Logout",
  username_label: "Le Username",
  password_label: "Le Password",
  login_label: "Le login",
  failed_login: "Le Failed login",
  attempting_login: "Je suis logging in...",
  welcome_dialog_title: "Bonjour",
  welcome_dialog_text: "Ello!"
});
