
/* -------------------------------------------------------------------------
 * !!! AUTOMATICALLY GENERATED CODE !!!
 * -------------------------------------------------------------------------
 * This file was automatically generated by the OrangeBits compiler.  
 * Compiled on:  13/01/2013 01:45:28
 * Compiled by: ALEX-PC\Alex
 * Source: E:\Project\GitHub\SpaceTrekkers\client-src\js\app.coffee      
 * -------------------------------------------------------------------------*/



define(["backbone", "backbone.marionette", "router", "modules/user/UserModule", "views/navbar/NavBarView", "views/plainOldTemplate/PlainOldTemplate"], function(Backbone, Marionette, Router, UserModule, NavBarView, PlainOldTemplate) {
  "use strict";
  var app;
  app = new Marionette.Application({
    Models: {},
    Collections: {},
    Views: {
      desktopView: new PlainOldTemplate("templates/desktop/desktopTemplate.html"),
      navBarView: new NavBarView()
    },
    loadModules: function() {
      return this.module("UserModule", UserModule);
    }
  });
  app.addRegions({
    navBar: "#navBar",
    mainRegion: "#mainRegion"
  });
  app.addInitializer(function() {
    this.app_router = new Router(this);
    return this;
  });
  return app;
});
